### ISSUE TITLE
500 error from the datadog handler

### ISSUE THREAD

**Issue by urit** [DataDog/gae_datadog#2]
TypeError: GlobalStat is not JSON serializable

changed db to ndb

from google.appengine.ext.ndb import stats as db_stats

and 'timestamp' is a date so:

data_stats = db_stats.GlobalStat.query().get().to_dict()
data_stats['timestamp'] = str(data_stats['timestamp'])
stats['datastore'] = data_stats
            
Thanks

Uri

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/gae_datadog/pull/7
