### ISSUE TITLE
Will branch 'fixndb' merge to master?

### ISSUE THREAD

**Issue by EllisShen** [DataDog/gae_datadog#5]
Hi,
I encounter the same issue of "500 Internal server error" when accessing "db_stats.GlobalStat.all().get()".
Fortunately the problem get solved in branch 'fixndb', will the branch 'fixndb' get merged back to master soon?

**Comment by yannmh** [comment]
Apologies for the delay on this @EllisShen.

This PR has been pending for a very long time. As I  am taking ownership of the repository, I'll make the necessary to have it merged by the end of next week. Sorry again about this.

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/gae_datadog/pull/7.
